version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - admin
      - site
    networks:
      - app-network

  app:
    build:
      context: .
      target: production
      dockerfile: ./backend/Dockerfile
    # volumes:
    #   - ./backend/:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  admin:
    build:
      context: .
      dockerfile: ./admin/dockerfile
    networks:
      - app-network
  site:
    build:
      context: .
      dockerfile: ./site/dockerfile
    networks:
      - app-network

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: app123456
      MYSQL_DATABASE: teste-laravel
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
