FROM node:17 as build
ARG env=prod


WORKDIR /usr/local/app

COPY ./site/ /usr/local/app/
RUN npm install
RUN npm run build --prod

FROM nginx:latest
COPY --from=build /usr/local/app/dist/site /usr/share/nginx/html
COPY ./site/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80